CREATE TABLE  LOGIN_USER (
    ID                VARCHAR(20) NOT NULL,
    PASSWORD          VARCHAR(20) NOT NULL,
    VERSION           INTEGER     DEFAULT 0 NOT NULL,
    CONSTRAINT "LOGIN_USER_PK" PRIMARY KEY ("ID")
);

COMMENT ON TABLE LOGIN_USER IS 'ログインユーザ';
COMMENT ON COLUMN LOGIN_USER.ID IS 'ID';
COMMENT ON COLUMN LOGIN_USER.PASSWORD IS 'パスワード';
COMMENT ON COLUMN LOGIN_USER.VERSION IS 'バージョン';

INSERT INTO LOGIN_USER ( ID, PASSWORD, VERSION ) VALUES ('system','system',0);
INSERT INTO LOGIN_USER ( ID, PASSWORD, VERSION ) VALUES ('training','training',0);
INSERT INTO LOGIN_USER ( ID, PASSWORD, VERSION ) VALUES ('skill','skill',0);
INSERT INTO LOGIN_USER ( ID, PASSWORD, VERSION ) VALUES ('reference','reference',0);

CREATE TABLE  LOGIN_SAMPLE (
    ID                VARCHAR(20) NOT NULL,
    PASSWORD          VARCHAR(20) NOT NULL,
    VERSION           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "LOGIN_SAMPLE_PK" PRIMARY KEY ("ID")
);

COMMENT ON TABLE LOGIN_SAMPLE IS 'ログインサンプル';
COMMENT ON COLUMN LOGIN_SAMPLE.ID IS 'ID';
COMMENT ON COLUMN LOGIN_SAMPLE.PASSWORD IS 'パスワード ';
COMMENT ON COLUMN LOGIN_SAMPLE.VERSION IS 'バージョン';

INSERT INTO LOGIN_SAMPLE ( ID, PASSWORD ) VALUES ('test','test');
INSERT INTO LOGIN_SAMPLE ( ID, PASSWORD ) VALUES ('sample','sample');
INSERT INTO LOGIN_SAMPLE ( ID, PASSWORD ) VALUES ('hsql','hsql');
INSERT INTO LOGIN_SAMPLE ( ID, PASSWORD ) VALUES ('system','system');
